#!/usr/bin/env python
import numpy, csv, argparse
import matplotlib.pyplot as plt
from numpy.random import normal

# gaussian_numbers = normal(size=1000)
# plt.hist(gaussian_numbers)
# plt.title("Gaussian Histogram")
# plt.xlabel("Value")
# plt.ylabel("Frequency")
# plt.show()

parser = argparse.ArgumentParser(description='Analyse and plot from a pump-measure results file.')
parser.add_argument(
    'input_file',
    help='The path to the input .csv, as generated by pump-measure.py')
args = parser.parse_args()

print 'Analysing {}'.format(args.input_file)
df = open(args.input_file)
dr = csv.DictReader(df)
d = list(dr)
for r in d:
    for suffix, name in (('F_d', 'forward'), ('R_d', 'reverse')):
        plt.hist(numpy.array([float(r[k]) for k in r.keys() if (k[-3:] == suffix)]), normed=True)
        plt.title('{} (revs = {}, rate = {})'.format(name, str(r['revs']), str(r['rate'])))
        plt.show()